on: [push]
name: AML CI
jobs:
  build_and_test:
    name: AML CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: example
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: -- -i sample/sample.aml -o sample.json
